language: cpp
compiler:
  - gcc
addons:
  apt:
    packages:
    - lcov
script:
  # build 3PL, OffPiste lib
  - bash config.sh -3pl -lib -testsOFF
  # run tests and generate coverage report
  - bash config.sh -cov
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: ./OffPiste/install/lib/libOffPiste.so
  skip_cleanup: true
  draft: true
after_success:
  # upload results to codecov
  - bash <(curl -s https://codecov.io/bash) -f OffPiste/coverage/OffPiste.info -t 036e96ae-9cba-429d-9a52-78e9d28e2f35
