language: cpp

compiler:
  - gcc

jobs:
  include:
    - os: linux
    - os: osx
      # only build this on tagged commits, for publishing .dylib artifact
      if: tag IS present
      before_install:
        - brew install lcov

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - lcov
    - g++-7

script:
  # build 3PL, OffPiste lib
  - bash config.sh -3pl -lib -testsOFF CXX=g++-7 CC=gcc-7
  # run tests and generate coverage report
  - bash config.sh -cov CXX=g++-7 CC=gcc-7

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file:
    - OffPiste/install/lib/libOffPiste.dylib
    - OffPiste/install/lib/libOffPiste.so
    - OffPiste/include/*
  skip_cleanup: true
  on:
    tags: true

after_success:
  # upload results to codecov
  - bash <(curl -s https://codecov.io/bash) -f OffPiste/coverage/OffPiste.info -t 036e96ae-9cba-429d-9a52-78e9d28e2f35
